name: Build and Push Docker images

on:
  push:
    branches: [main]
    paths:
      - 'katib-adult/**'
      - 'katib-amazon/**'
      - 'dr-cnn-1024/**'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-adult:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Build and Push katib-adult
        run: |
          cd katib-adult
          docker build -t wdzomoaz/katib-adult:${{ github.sha }} .
          docker push wdzomoaz/katib-adult:${{ github.sha }}

  build-amazon:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Build and Push katib-amazon
        run: |
          cd katib-amazon
          docker build -t wdzomoaz/katib-amazon:${{ github.sha }} .
          docker push wdzomoaz/katib-amazon:${{ github.sha }}

  build-dr-cnn-1024:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Build and Push dr-cnn-1024
        run: |
          cd dr-cnn-1024
          docker build -t wdzomoaz/dr-cnn-1024:${{ github.sha }} .
          docker push wdzomoaz/dr-cnn-1024:${{ github.sha }}
